import 'package:payzo_books/import_data.dart';

Widget noVendorDetailFoundPage({required BuildContext context}) {
  return SingleChildScrollView(
    child: Padding(
      padding: const EdgeInsets.only(left: 24, right: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // headerTextAndWidgets(
          //     headerText1: '',
          //     headerText2: '',
          //     title1: AppText.call,
          //     title2: AppText.mail,
          //     title3: AppText.msg,
          //     title4: AppText.more,
          //     title5: AppText.delete,
          //     img1: AppImages.call,
          //     img2: AppImages.mail,
          //     img3: AppImages.msg,
          //     img4: AppImages.more,
          //     img5: AppImages.delete,
          //     isonTap1Needed: true,
          //     isonTap4Needed: true,
          //     isonTap2Needed: false,
          //     isonTap5Needed: false,
          //     isonTap3Needed: false,
          //     onTap3: () {},
          //     onTap1: () {},
          //     onTap2: () {},
          //     onTap4: () {},
          //     onTap5: () {}),
          headerTextAndWidgets(
            headerText1: 'vendor.companyName',
            headerText2: 'vendor.emailAddress',
            imgName1: AppText.call,
            imgName2: AppText.mail,
            imgName3: AppText.msg,
            imgName4: AppText.edit,
            img1: AppImages.call,
            img2: AppImages.mail,
            img3: AppImages.msg,
            img4: AppImages.editWhite,
            isMailNeeded: true,
            isCallNeeded: true,
            isEditNeeded: true,
            callOnTap: () {},
            mailOnTap: () {},
            msgOnTap: () {},
            editOnTap: () {},
          ),
          GapSpace.height35,
          financialCard(
            state: '',
            city: '',
            companyName: '',
            primaryContactName: '',
            mobileCode: '',
            phoneNumber: '',
            emailAddress: '',
          ),
          GapSpace.height20,
          customExpandableSection(context,
              isContentTypeString: false,
              title: AppText.billingAdrs,
              contentWidget: null,
              isPrefixIconNeeded: true,
              prefixImg: AppImages.locationPin),
          GapSpace.height20,
          customExpandableSection(context,
              isContentTypeString: false,
              title: AppText.shippingAdrs,
              contentWidget: null,
              isPrefixIconNeeded: true,
              prefixImg: AppImages.locationPin),
          GapSpace.height20,
          customExpandableSection(
            context,
            isContentTypeString: false,
            title: AppText.primaryContct,
            contentWidget: null,
            isPrefixIconNeeded: false,
          ),
          GapSpace.height20,
          customExpandableSection(
            context,
            isContentTypeString: true,
            title: AppText.regionDetails,
            content: '',
            isPrefixIconNeeded: false,
          ),
          GapSpace.height20,
          customExpandableSection(
            context,
            title: AppText.otherDetails,
            isContentTypeString: false,
            contentWidget: vendorDetailsContent(
              // partyId: vendor.partyId,
              partyType: '',
              // transactionId: ''
            ),
            isPrefixIconNeeded: false,
          ),
          GapSpace.height40,
        ],
      ),
    ),
  );
}
