// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-i99_mbMEWhKPGZmDXqaYm_GbtBUIJAw',
    appId: '1:203720179569:web:2183f76a984f2e1d31c0d0',
    messagingSenderId: '203720179569',
    projectId: 'payzo-books',
    authDomain: 'payzo-books.firebaseapp.com',
    storageBucket: 'payzo-books.firebasestorage.app',
    measurementId: 'G-TD0CDFFHZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WI2P7a5vNeuN-g47l9TfPI1apfPlPd4',
    appId: '1:203720179569:android:c7f11c25f24e3c3d31c0d0',
    messagingSenderId: '203720179569',
    projectId: 'payzo-books',
    storageBucket: 'payzo-books.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9V0HaFVLtT3aaGiSqPO2trdyyRwf_rY',
    appId: '1:203720179569:ios:5daf9216100cc1f731c0d0',
    messagingSenderId: '203720179569',
    projectId: 'payzo-books',
    storageBucket: 'payzo-books.firebasestorage.app',
    iosBundleId: 'com.its.payzobooks.payzoBooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9V0HaFVLtT3aaGiSqPO2trdyyRwf_rY',
    appId: '1:203720179569:ios:5daf9216100cc1f731c0d0',
    messagingSenderId: '203720179569',
    projectId: 'payzo-books',
    storageBucket: 'payzo-books.firebasestorage.app',
    iosBundleId: 'com.its.payzobooks.payzoBooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-i99_mbMEWhKPGZmDXqaYm_GbtBUIJAw',
    appId: '1:203720179569:web:57c671923cffb6f531c0d0',
    messagingSenderId: '203720179569',
    projectId: 'payzo-books',
    authDomain: 'payzo-books.firebaseapp.com',
    storageBucket: 'payzo-books.firebasestorage.app',
    measurementId: 'G-YRLWFY06MG',
  );
}
